### ISSUE TITLE
No longer working in tvOS 15

### ISSUE THREAD

**Issue by KibosJ** [lukasroegner/homebridge-apple-tv-remote#105]
I know it's a beta, just wanted to give a heads up that this doesn't work in tvOS 15

**Comment by jkreileder** [comment]
Yea, I see this too. The plugin just logs 

```
[6/13/2021, 7:04:55 PM] [Apple TV Platform] [Apple HB] Error while connecting: Error: Apple TV not found while scanning.
[6/13/2021, 7:04:58 PM] [Apple TV Platform] [Apple HB] Error while connecting: Error: Apple TV not found while scanning.
[6/13/2021, 7:04:58 PM] [Apple TV Platform] [Apple HB] Error while connecting for heartbeat: Error: Apple TV not found while scanning.
[6/13/2021, 7:05:02 PM] [Apple TV Platform] [Apple HB] Error while connecting: Error: Apple TV not found while scanning.
[6/13/2021, 7:05:09 PM] [Apple TV Platform] [Apple HB] Error while connecting: Error: Apple TV not found while scanning.
```

Trying to re-pair the device with ```appletv pair``` hangs after sending the initial ```DEVICE_INFO_MESSAGE```.

**Comment by njuart** [comment]
Yes, confirmed, can't pair also after tvOS 15 public beta 2. Any possible ideas? Thx @lukasroegner

**Comment by njuart** [comment]
Did anyone manage to connect successfully? For me it also hangs after sending the initial DEVICE_INFO_MESSAGE. Looks like this project is on the hold and no longer supported. Sad, very useful one.

**Comment by MatGriffin** [comment]
Same, fails on tvOS 15 beta 2

**Comment by kdbaustert** [comment]
Confirmed also can't pair

**Comment by Christian-CFP** [comment]
@lukasroegner Any news for an update on this?

**Comment by njuart** [comment]
I've been digging a bit, and it looks like issue is present also in pyatv project which is described here https://github.com/postlund/pyatv/issues/1168 @lukasroegner Something with MRP and Companion

**Comment by MsCopernic** [comment]
Same here, it's not even possible to detect an Apple TV

**Comment by Aekung** [comment]
I shouldn't have updated loll. Did the update accidentally and the problem occurs. Any news on this?

**Comment by BrianTillman** [comment]
+1

**Comment by limey7291** [comment]
Same with me Beta3

**Comment by slurpera** [comment]
+1

**Comment by Christian-CFP** [comment]
+1 million but it does not care @lukasroegner

**Comment by slurpera** [comment]
> +1 million but it does not care @lukasroegner

I think it is an issue with one of the dependencies. Apple deprecated the old remote api on the Apple TV. Sigh...

**Comment by njuart** [comment]
I think this plugin is maintained no more, and won't be, as iOS 15 deprecated mechanism that was used previously, so it requires refactoring, as I understood.

**Comment by Willygoat1** [comment]
Any chance of this working in tvOS15 at some point?

**Comment by bsharper** [comment]
@Willygoat1 Probably. I'm hopeful. Developer postlund has done lots of work with the new Companion protocol and has implemented some Companion remote control functions in the python library `pyatv`. Right now controlling the Apple TV using this protocol works with tvOS 14 but not tvOS 15 beta for some reason. It's possible that the beta simply has bugs that prevent it from working with this implementation, or that additional changes will be required to get it to work.

**Comment by postlund** [comment]
By the looks of it, MRP is going away in tvOS 15. Or that's note entirely true: it is moving. Instead of being its own protocol, it will continue to exist as a special stream type within AirPlay 2. So it's basically possible to setup a channel over AirPlay 2 that carries MRP messages like we do today. It's a bit tricky and I've spent a *lot* of hours figuring out how that work and started documenting it in the pyatv documentation [here](https://pyatv.dev/documentation/protocols/#remote-control). I have not started implementing it in pyatv yet however, that will be the next step and I will probably find a few things to correct in my findings so far. But what's written there is basically what you need to do to get things working again in tvOS 15. Just wanted to let you all know 👍

(Companion can be used for remote control commands, but isn't necessary since MRP can deal with that like before)

**Comment by MatGriffin** [comment]
Thank you for all your work. 👍

**Comment by MatGriffin** [comment]
Nice, but how do I install this? Using Homebridge on Raspberry PI, tried the pip3 install pyatv but command not found error.

**Comment by postlund** [comment]
Should be possible to run via docker now:

    docker run --rm --network=host ghcr.io/postlund/pyatv:master atvremote scan

**Comment by naor1** [comment]
Hi @postlund 

 I was able to get the token with docker but when I put it in the plugin I get an error that its not correct.
also if I try it with CLI its working and I can get the song details..

Any idea how I can make the plugin work with It?

Thanks.

**Comment by postlund** [comment]
@naor1 What are you trying more exactly? Some commands and error messages would help a lot.

**Comment by naor1** [comment]
Im trying to connect to the new tvOS 15 with the plugin homebridge-apple-tv-remote.
With tvOS 14 im able to connect and control the Apple TV but after updating to 15 I can't, so I tried your suggestion here to get the credentials with docker and I was able to do that but this credentials are not working in the plugin.

I get this error in Homebridge log: "Credentials are invalid. Make sure that you copied them correctly."

**Comment by postlund** [comment]
This plugin does not support tvOS 15 so that won't work. The credentials you get are only valid for pyatv.

**Comment by naor1** [comment]
Ahh that make sense..
Thanks.

**Comment by arkadicolson** [comment]
Is there any support coming for tvOS in the future for this plugin?

**Comment by DJay-X** [comment]
@lukasroegner Any news regarding tvOS 15.
I just noticed today that there are many errors in the log.

```
[22.9.2021, 21:25:37] [AppleTvPlatform] [Apple TV] Error while connecting for heartbeat: Error: Apple TV not found while scanning.
[22.9.2021, 21:25:41] [AppleTvPlatform] [Apple TV] Error while connecting: Error: Apple TV not found while scanning.
```
And of course appletv pair is also not working anymore.
```
pi@raspberrypi-3BPlus:~ $ appletv pair
⠋ Scanning for Apple TVs...(node:1366) Warning: Accessing non-existent property 'padLevels' of module exports inside circular dependency
(Use `node --trace-warnings ...` to show where the warning was created)
No Apple TVs found on the network. Try again.
```

I hope you can fix this. Wouldn't want to miss homebridge-apple-tv-remote

Thanks in advance.

**Comment by DarKOrange75** [comment]
Hi @postlund
will this plugin work with iOS15 at some point or should we forget about it and find another solution?

**Comment by postlund** [comment]
@DarKOrange75 I don't know as I don't maintain it. I guess it's up to @lukasroegner if he wants to continue maintain it or if someone else decides to step in and add support for tvOS 15.

**Comment by flinke-flasche** [comment]
@lukasroegner 
Do you think you can / will fix that?

**Comment by NorthernMan54** [comment]
Do we have someone with the ability and time to resolve this based on the fix by @postlund ?  Without looking at this in detail am thinking that the upstream package node-AppleTV-x needs most of the effort.

**Comment by shemege** [comment]
I made some research and implemented from scratch. Downloaded homebridge-cmd4 plugin and playing with atvremote [https://github.com/postlund/pyatv](url)

`atvremote -s IP_address_of_ATV --airplay-credentials aplay_creds power_state`
`atvremote -s IP_address_of_ATV --airplay-credentials aplay_creds turn_off`
`atvremote -s IP_address_of_ATV --airplay-credentials aplay_creds turn_on`

homebridge_cmd4:
`{
            "platform": "Cmd4",
            "name": "Cmd4",
            "accessories": [
                {
                    "type": "Switch",
                    "name": "TV",
                    "on": false,
                    "state_cmd": "bash appletv.sh",
                    "polling": [
                        {
                            "on": false,
                            "interval": 5,
                            "timeout": 5000
                        }
                    ],
                    "interval": 5,
                    "timeout": 5000
                }
            ]
        }`

**Comment by MatGriffin** [comment]
I now have Apple TV on/off control

I installed https://pyatv.dev
Once installed I then paired my Apple TV using the command
`atvremote -s APPLETVIPADDRESS --protocol companion pair`

I copied the long string of numbers and created 3 shell scripts, adding my IP address of the ATV and the long string of numbers to each
 
appletv_on.sh
`atvremote -s IP_address_of_ATV --airplay-credentials aplay_creds turn_on`

appletv_off.sh
`atvremote -s IP_address_of_ATV --airplay-credentials aplay_creds turn_on`

appletv_state.sh
`atvremote -s IP_address_of_ATV --airplay-credentials aplay_creds turn_on`

I copied those on to my raspberry pi at /var/lib/homebridge

I then installed homebridge-script2-ventrilo Homebridge plugin which is a simple plugin that can run the scripts and added the following config
```
{
    "accessory": "Script2",
    "name": "ATV",
    "on": "/var/lib/homebridge/appletv_on.sh",
    "off": "/var/lib/homebridge/appletv_off.sh",
    "state": "/var/lib/homebridge/appletv_state.sh",
    "fileState": "/var/lib/homebridge/script1.flag",
    "on_value": "true"
}

```

In Home app I can now turn on and off the ATV :)

**Comment by shemege** [comment]
@DarKOrange75 Try using full path and make your scripts executable `chmod +x script.sh`

**Comment by matcik890** [comment]
I also have a problem, the script works through SSH commands, but the device does not work through the homebridge plugin.

**Comment by DarKOrange75** [comment]
> @DarKOrange75 try `chmod +x /home/pi/.local/bin/atvremote`. What's output command `ls -lah /home/pi/.local/bin/`. I mean who is owner of atvremote and it's permission?

The owner is pi
<img width="410" alt="Capture d’écran 2021-10-18 à 23 30 13" src="https://user-images.githubusercontent.com/40524270/137809456-ca439427-4919-46f8-a3fc-232c5aaa2ef9.png">

**Comment by shemege** [comment]
@DarKOrange75 @matcik890 Simply try `chmod 777 atvremote`. It's definitely permission issue. One has owner pi, and another is owner homebridge.

**Comment by matcik890** [comment]
> @DarKOrange75 @matcik890 Просто попробуйте`chmod 777 atvremote`, или `sudo chmod 777 atvremote`это определенно проблема с разрешением. У одного есть владелец pi, а у другого-владелец домашнего моста. Я не использую его на raspberry, я нахожусь в виртуальной среде на сервере Ubuntu.
![123](https://user-images.githubusercontent.com/55558797/137882193-c43b50bc-6c9d-4b78-a66a-5d900f2d1e12.jpg)
I just gave full access to all files that are related to the work of this plugin, but it didn't work(

**Comment by matcik890** [comment]
> homebridge ALL=(ALL) NOPASSWD: ALL



> @matcik890 ХОРОШО, попробуй это:
> 
> Многие операции, выполняемые Homebridge Config UI X, такие как установка плагинов, обновление Homebridge и просмотр журналов, могут потребовать прав суперпользователя. Вы можете запустить службу Homebridge от имени root или включить опцию **sudo** в конфигурации.
> 
> `"platforms": [ { "platform": "config", "name": "Config", "port": 8080, "sudo": true } ]`
> 
> Когда включен режим sudo, Конфигурация домашнего моста UI X будет использовать sudo при установке, удалении или обновлении подключаемых модулей, просмотре журналов с использованием журналов Из файла или журналов Из метода Systemd, а также при обновлении домашнего моста. Он не будет использоваться для журналов Пользовательских команд или пользовательских команд перезапуска.
> 
> Судо без пароля требуется
> 
> Для работы в режиме sudo требуется sudo без пароля. Вы можете включить sudo без пароля, добавив эту запись в нижнюю часть `/etc/sudoers`файла (используйте visudo для редактирования файла!):
> 
> `homebridge ALL=(ALL) NOPASSWD: ALL` или `pi ALL=(ALL) NOPASSWD: ALL` замените homebridge фактическим пользователем, от имени которого вы запускаете Homebridge.

Thanks for the advice! But I do not know if I understood you correctly. I added the string "sudo" to the homebridge configuration: true,

"bridge": {
"name": "Homebridge 34C1",
"username": "0E:87:6D:97:34:C1",
"port": 51248,
"sudo": true,
"ping": "999-99-999"


and also I checked /etc/sudoers, but it already contains pi ALL=(ALL) NOPASSWD: ALL


Maybe I didn't understand something, I'm not very good at subtleties
![1345](https://user-images.githubusercontent.com/55558797/137992490-733e8345-c593-4106-9ea7-33e22eda0646.jpg)
.

**Comment by NorthernMan54** [comment]
100% agreed on the alexa voice control as the way to go here.  Is your wording with Alexa clumsy now based on the workaround?

In my setup, turning off/on and pause/resume were one of the highest used functions.

**Comment by cristian5th** [comment]
@njuart, all this is so weird! In the latest capture that you sent, the issue is that the shell scripts cannot be found at the indicated folder. I'm afraid I don't understand why this is happening. Why don't you try to contact @ztalbot2000, owner of homebridge-cmd4? He might see easier why you are getting this strange issue.

@NewmansHub, that would be great but I do not have the knowledge. As far as I understood, @NorthernMan54 has been working exactly on that kind of solution. Maybe he is almost ready for a release.

**Comment by shemege** [comment]
Hi,
I you have trouble with atvremote ( like me ) with version ATV 15.1.1 (lastest version TVOS) like this:
`ValueError: could not convert string to float: '15.1.1'`
try reinstall atvremote with command (devel version):
`pip3 install --upgrade git+https://github.com/postlund/pyatv.git`

**Comment by postlund** [comment]
> Hi,
> I you have trouble with atvremote ( like me ) with version ATV 15.1.1 (lastest version TVOS) like this:
> `ValueError: could not convert string to float: '15.1.1'`
> try reinstall atvremote with command (devel version):
> `pip3 install --upgrade git+https://github.com/postlund/pyatv.git`

That error was fixed in pyatv 0.9.3, so as long as you have that version or later you should be fine.

    pip install --upgrade pyatv

Should do the trick.

**Comment by njuart** [comment]
@cristian5th I finally figured it out. It was lying on a surface, I've played with timeout value. So for me it worked at 10000 timeout.

**Comment by cristian5th** [comment]
> @cristian5th I finally figured it out. It was lying on a surface, I've played with timeout value. So for me it worked at 10000 timeout.

Hmmm. 10 seconds timeout. I wonder why was this an issue. Any idea why you where experiencing this?

Anyway, I'm glad that you got it working. I hope we can enjoy it for many years before something is broken again.

**Comment by njuart** [comment]
> > @cristian5th I finally figured it out. It was lying on a surface, I've played with timeout value. So for me it worked at 10000 timeout.
> 
> Hmmm. 10 seconds timeout. I wonder why was this an issue. Any idea why you where experiencing this?
> 
> Anyway, I'm glad that you got it working. I hope we can enjoy it for many years before something is broken again.

Not sure, maybe it wasn't enough time to process. But, I went further and put Cmd4 to a child bridge, and now it works flawlessly with 4000 timeout.

**Comment by lennartvava** [comment]
@cristian5th thanks for your solution. I followed it and bumped into one issue. When the polling is executed I get the following error:
```
getValue On function failed for Apple TV Power cmd: bash /var/lib/homebridge/appletv_powerstate.sh Get 'Apple TV Power' 'On' Failed.  Generated Error: Error: Command failed: bash /var/lib/homebridge/appletv_powerstate.sh Get 'Apple TV Power' 'On'
Traceback (most recent call last):
  File "/home/pi/.local/bin/atvremote", line 6, in <module>
    from pyatv.scripts.atvremote import main
ModuleNotFoundError: No module named 'pyatv'
```

For some reason the pyatv module is non-existing while polling and executing atvremote. When executing the script manually in CLI, all is fine and I get good results. Any ideas?

**Comment by cristian5th** [comment]
> @cristian5th thanks for your solution. I followed it and bumped into one issue. When the polling is executed I get the following error:
> 
> ```
> getValue On function failed for Apple TV Power cmd: bash /var/lib/homebridge/appletv_powerstate.sh Get 'Apple TV Power' 'On' Failed.  Generated Error: Error: Command failed: bash /var/lib/homebridge/appletv_powerstate.sh Get 'Apple TV Power' 'On'
> Traceback (most recent call last):
>   File "/home/pi/.local/bin/atvremote", line 6, in <module>
>     from pyatv.scripts.atvremote import main
> ModuleNotFoundError: No module named 'pyatv'
> ```
> 
> For some reason the pyatv module is non-existing while polling and executing atvremote. When executing the script manually in CLI, all is fine and I get good results. Any ideas?

I have no clue on what can happen. Maybe it is a different Python installation what is being executed from CLI and from Homebridge and pyatv is only correctly installed into one of those?

@postlund is the creator of this pyatv wonder. Maybe he has some ideas about what to do or how to look for more info.

**Comment by postlund** [comment]
This is a long thread now, so it's hard to get an overview of the problem. But it obviously has something to do with environments and paths. I would suggest (as the same user running homebridge):

    python3 -m venv ~/pyatv_venv
    source ~/pyatv_venv/bin/activate
    pip install pyatv

Then call `~/pyatv_venv/bin/atvremote` directly.

**Comment by lennartvava** [comment]
> This is a long thread now, so it's hard to get an overview of the problem. But it obviously has something to do with environments and paths. I would suggest (as the same user running homebridge):
> 
> ```
> python3 -m venv ~/pyatv_venv
> source ~/pyatv_venv/bin/activate
> pip install pyatv
> ```
> 
> Then call `~/pyatv_venv/bin/atvremote` directly.

Installing pyatv as the homebridge user did the trick. It seems this user didn't have access to it.
Thanks @cristian5th and @postlund for the insane speed of response.

**Comment by NorthernMan54** [comment]
@cristian5th Well, I'm finally finished my version of 'Homebridge-cmd-television', that works with homebridge-alexa.  I'm finally able to control my TV again with Alexa.  Working functions include, turn on, turn off, pause and play.  Also on/off status in the Home App works as well.

If you want to give it a try, my code is located here - https://github.com/NorthernMan54/homebridge-cmd-television

PS No changes were required to my homebridge-alexa plugin or its configuration as well

**Comment by MatGriffin** [comment]
> @cristian5th Well, I'm finally finished my version of 'Homebridge-cmd-television', that works with homebridge-alexa. I'm finally able to control my TV again with Alexa. Working functions include, turn on, turn off, pause and play. Also on/off status in the Home App works as well.
> 
> If you want to give it a try, my code is located here - https://github.com/NorthernMan54/homebridge-cmd-television
> 
> PS No changes were required to my homebridge-alexa plugin or its configuration as well

Thanks but on boot after installing your plug-in I get

 ERROR LOADING PLUGIN homebridge-cmd-television:
[```
12/11/2021, 16:20:48] Error: Cannot find module 'request'
Require stack:
- /usr/local/lib/node_modules/homebridge-cmd-television/index.js
- /usr/local/lib/node_modules/homebridge/lib/plugin.js
- /usr/local/lib/node_modules/homebridge/lib/pluginManager.js
- /usr/local/lib/node_modules/homebridge/lib/server.js
- /usr/local/lib/node_modules/homebridge/lib/cli.js
- /usr/local/lib/node_modules/homebridge/bin/homebridge
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:902:15)
    at Function.Module._load (internal/modules/cjs/loader.js:746:27)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:93:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge-cmd-television/index.js:1:15)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12)
    at Module.require (internal/modules/cjs/loader.js:974:19)
```

and lots of other plugins now no longer run

```
[12/11/2021, 16:20:48] No plugin was found for the platform "Hue" in your config.json. Please make sure the corresponding plugin is installed correctly.
[12/11/2021, 16:20:48] No plugin was found for the platform "TuyaLan" in your config.json. Please make sure the corresponding plugin is installed correctly.
[12/11/2021, 16:20:48] No plugin was found for the platform "zigbee2mqtt" in your config.json. Please make sure the corresponding plugin is installed correctly.
[12/11/2021, 16:20:48] No plugin was found for the platform "TuyaPlatform" in your config.json. Please make sure the corresponding plugin is installed correctly.
[12/11/2021, 16:20:48] No plugin was found for the platform "Wemo" in your config.json. Please make sure the corresponding plugin is installed correctly.
[12/11/2021, 16:20:48] No plugin was found for the accessory "HTTP-SWITCH" in your config.json. Please make sure the corresponding plugin is installed correctly

Any ideas?

```

**Comment by NorthernMan54** [comment]
@MatGriffin pls try installing again, I changed the config around the module 'request'

This is what I get when installing

```
npm i -g https://github.com/NorthernMan54/homebridge-cmd-television
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
+ homebridge-cmd-television@2.0.0
added 48 packages from 59 contributors in 6.282s
```

PS For issues with plugin, pls raises issues directly against its repo.

**Comment by ztalbot2000** [comment]
A clean bash environment can be had wit:

env -i bash --noprofile --norc

Run your script with that bash shell and then see what your script does
when you run it from there.  Scripting is painful when you realize that
your bashrc file can have great influence on what you do. One of the
reasons I do not do anything special with my .bashrc.

Ttyl,
John

**Comment by justinmm2** [comment]
Hi @NorthernMan54 ! Thank you for this; I'd normally try to say so in a separate forum, but wanted to comment here in case others come across with questions. I'm running the Homebridge Synology docker container, and can offer a few tips to those doing the same. (One is that you can launch a Terminal in the container from the Homebridge UI!)

But first, if anyone has issues where the "npm i" command to install the plugin from git insists on using ssh, despite git configuration overrides, this solved my issue; it no longer insisted on using ssh for cloning.
$ npm config set ssl-strict=false

As for the rest of it, here are the commands I ran. (I assume you can combine apk packages into one command)
# Ran inside the homebridge container on the synology (via web console)
apk add gcc openssh python3-dev rust
pip3 install --upgrade pip
# pip3 install wheel ## can't recall if this was required or not
pip3 install cryptography
pip3 install pyatv
atvremote scan
atvremote -s <ATV IP address> --protocol companion pair
npm config set ssl-strict=false
npm i -g https://github.com/NorthernMan54/homebridge-cmd-television

I am experiencing a strange error where my TV turns on ~30 seconds after I turn it off sometimes, but I don't see anything in the Homebridge debug logs, so I will assume it's something else for the moment!

**Comment by NorthernMan54** [comment]
@justinmm2 Tks for that fragment, I added it to the README

https://github.com/NorthernMan54/homebridge-cmd-television

**Comment by justinmm2** [comment]
One more for both @lukasroegner and @NorthernMan54 : in order to get it working now (on my ATV 4K/2017), I had to change the config to use "wakeup" and "suspend"; the example "wake"/"turn_off"/etc. commands did not work. There was also no need to do a second "suspend" with a sleep or anything.

I can't comment on the propriety of doing these things widely; again, I include it for intrepid Googlers, and devs who may encounter the same thing(s). This was the result of going down a rabbit hole when I realized that the turn_off command was executing a select command; when I was trying to turn my TV off, I noticed it subtly going forward into menus and even playing things, depending on where my "cursor" was.

**Comment by postlund** [comment]
> I suspect these are the result of pyatv modifications, but can't comment on the propriety of doing these things widely; again, I include it for intrepid Googlers, and devs who may encounter the same thing(s). This was the result of going down a rabbit hole when I realized that the turn_off command was executing a select command; when I was trying to turn my TV off, I noticed it subtly going forward into menus and even playing things, depending on where my "cursor" was.

If you only provide AirPlay credentials, then pyatv will use "navigation" to turn off the device as there's no support in the protocol to do it any other way. If you also provide Companion credentials, the pyatv will (automatically) use a proper method of turning off the device as that protocol supports it natively. It's the same way the Shortcuts app works. You should not use `suspend` and `wakeup` as they are deprecated and will be removed soon.

**Comment by NorthernMan54** [comment]
@postlund Tks for that tip, I finally went and updated my config and it now works better than before.  For folks watching, my current config for my version of homebridge-cmd-television

```
"oncmd": "atvremote --id 08:66:98:D4:CF:79 --companion-credentials `cat ~/.homebridge/atv_companion.cred` turn_on",
"offcmd": "atvremote --id 08:66:98:D4:CF:79 --companion-credentials `cat ~/.homebridge/atv_companion.cred` turn_off",
"pausecmd": "atvremote --id 08:66:98:D4:CF:79 --airplay-credentials `cat ~/.homebridge/atv_airplay.cred` pause",
"playcmd": "atvremote --id 08:66:98:D4:CF:79 --airplay-credentials `cat ~/.homebridge/atv_airplay.cred` play",
"powerstatecmd": "atvremote --id 08:66:98:D4:CF:79 --airplay-credentials `cat ~/.homebridge/atv_airplay.cred` power_state"
```

**Comment by napo-leon** [comment]
Hello all,
Thanks to your different workaround, I'm now aible to get the power on / off status of my apple TV in HOME. It's work well and very reactive in.
But when I try to create an automation like (when ATV on, turn on my led strip OR when ATV off, turn of my led strip) the trigger doesn't work...
I have nothing in the console of homebridge. 

Some idea about this trigger issue? Thanks a lot

**Comment by cristian5th** [comment]
Hello Napoleon :)

Which one of the proposed solutions are you using?

If I understood right, @NorthernMan54 solution ([https://github.com/NorthernMan54/homebridge-cmd-television](url)) is not retrieving the state of the Apple TV unless you call one of the commands from the plugin. In other words, if you use the plugin via Alexa to turn the Apple TV ON, then you will get the ON status and your led strip will turn ON with the automation. But if you simply use the remote to turn on the Apple TV, nothing will trigger the plugin to get the status and your automation will not work. Please, somebody correct me if what I just wrote is wrong.

If you use the CMD4 solution as proposed by @shemege and @njuart, then you can make the CMD4 plugin to read the Apple TV state every x seconds and use that information for your automation. This is the solution that I'm using because I had the same interest as you. I have the CMD4 plugin pooling the Apple TV state every 5s and all is working fine. I created this project just to remember what needs to be done ([https://github.com/cristian5th/homebridge-appletv](url))

**Comment by napo-leon** [comment]
Hello @cristian5th I'm using an hybrid solution:

SH script (on my mac mini):

> if atvremote -s IPADRESS --airplay-credentials CRED power_state | grep -q PowerState.On;
> then
>     echo "1"
> else
>     echo "0"
> fi

Json config in Homebridge:

> {"platform": "Cmd4",
> "name": "Cmd4",
> "accessories": [
> 	{"type": "Switch",
> 	"name": "Apple TV",
> 	"on": true,
> 	"state_cmd": "bash ~/Documents/Script/appletv.sh",
> 	"polling": [
> 	{
> 	"on": true,
> 	"interval": 5,
> 	"timeout": 5000}],
> "interval": 5,
> "timeout": 5000}


This one work well to get status. But not for trigger. If someone could check this config to know if the issue is due to my script or if it's an Home limitation.

Thanks a lot

**Comment by cristian5th** [comment]
Yes, your script should be good to get the status.

In order to trigger, you need another script. pytv command for trigger will be something like this:
`atvremote --id ${ATV_id} --companion-credentials ${companion_credentials} turn_off`

As written by @postlund earlier, it is better to use companion-credentials to send commands and airplay-credentials to get the status. Depending if you do everything in one single sh file or not, then you will need to add more switches to your HB configuration or not.

Check my project. You have everything into one single script for power and play/pause command and status.

**Comment by napo-leon** [comment]
I'm not sur to understand very well (due to my english level :) ).
My only needs is to have in home a kind of switch on/off of the actual state of apple tv (refreshed every 5 second).
And use this switch only to trigger another action (I never use this switch to power on off my ATV).
If I want the most simple script what do you advise?

Thanks a lot for your help!!!

**Comment by cristian5th** [comment]
Your script is enough if you just want to receive the status of the Apple TV power. If it is not working, then you may need to find some syntax error. At first sight, I cannot see any.

Based on what is working for me, I would modify your script like this, but again, I don't know why your script is not working.

_Note: replace THE_REAL_ID_OF_YOUR_ATV and THE_REAL_AIRPLAY_CREDENTIALS_OF_YOUR_ATV with your data._

**appletv.sh**
```
#!/bin/bash
ATV_POWER_STATE=$(atvremote --id THE_REAL_ID_OF_YOUR_ATV --airplay-credentials THE_REAL_AIRPLAY_CREDENTIALS_OF_YOUR_ATV power_state)
if [ "${ATV_POWER_STATE}" = "PowerState.On" ]
then
    printf "1\n"
else
    printf "0\n"
fi
exit 0
```

**Json config in Homebridge**
```
{
    "platform": "Cmd4",
    "name": "Cmd4",
    "interval": 5,
    "timeout": 4000,
    "debug": false,
    "stateChangeResponseTime": 3,
    "queueTypes": [
        {
            "queue": "A",
            "queueType": "WoRm"
        }
    ],
    "accessories": [
        {
            "type": "Switch",
            "displayName": "Apple TV",
            "on": "FALSE",
            "queue": "A",
            "polling": [
                {
                    "characteristic": "on"
                }
            ],
            "state_cmd": "bash ~/Documents/Script/appletv.sh"
        }
}
```

**Comment by napo-leon** [comment]
I have test tour proposal.

when I run in terminal the script sh it’s Work Well.
But in home bridge the Switch stay off. 

If I Switch manually on… It’s work as trigger… but stay on Just few seconds.
I think the cmd4 doesnt keep the on state.

Do you have idea?

**Comment by napo-leon** [comment]
Sorry for my prévoies message it’s my faut (path issue) non it’s work but the triggering doesn’t work. 

When I turn on my Apple TV the switch go On valse but do not start my led…
I dont Know why this trigger mechanism doesn’t work in Home app…

Nevertheless thanks a lot for your support

**Comment by cristian5th** [comment]
I think you had some remaining of your previous scripts that were causing trouble. Now, you write that the switch goes on when you turn on the ATV. That means it is working correctly.

If your automation is still failing, it might also be because you have created it when you were using the previous script. Try to delete the automation and create it again. I can assure you that it works perfectly. This is how mine looks like:

![IMG_0333](https://user-images.githubusercontent.com/35431417/149998082-6c7c813f-c73d-4121-8969-4648d662f3dd.jpeg)

**Comment by napo-leon** [comment]
I have found a solution. Just delete and my homebridge in home and now it’s work!! Im so happy. Thanks a lot

**Comment by Aekung** [comment]
I just want to share my way of solution after playing around with your guys methods for hours. I think it's the easiest way for me and it's already suit all my use case. However, I just have to pre-inform first that my method will only work with 'On/Off' and also reporting the correct 'power_state' of the Apple TV no matter if you are turning in off/on in HomeKit or your Apple TV remote. As I don't need the 'Play/Pause' state for my implementation, I didn't spend time trying on that.

I use 'Homebridge Cmdswitch2 No Logs' plugin as it's the plugin I'm currently using for my PS5.

1. Instally pyatv with `pip install pyatv` . Note that you may need 'sudo' in order to make it work.
2. After the installation is completed, scan for the credential of your Apple TV with `sudo atvremote scan`. Note down the Mac Address and IP Address of the Apple TV you want to connect to.
3. Pair your Apple TV with sudo `atvremote -s {YOUR-APPLE-ID-IP-ADDRESS} --protocol companion pair`. You will be asked to enter the 6 digits showing on your tv onto the terminal window. After than, take note of the credential showing on the terminal screen.
4. Install the 'Homebridge Cmdswitch2 No Logs'. This one comes with Homebridge UI X setting page so it's gonna be easy for you on the next step.
5. Open the setting page of 'Homebridge Cmdswitch2 No Logs' and create new switches platform with these settings

```
Name: Name your Apple TV

On Command: `atvremote -s 10.46.1.143 --airplay-credentials {YourAppleTVCredentialHere} turn_on` You may need it fill in the full path of your command if this doesn't work. For example, you may need to use /home/pi/.local/bin/atvremote instead of just atvremote

Off Command: `atvremote -s 10.46.1.143 --airplay-credentials {YourAppleTVCredentialHere} turn_off`

State Command: `atvremote -s 10.46.1.143 --airplay-credentials {YourAppleTVCredentialHere} power_state | grep -i 'PowerState.On'`. You may notice that I have grep -i command after the power_state command. This is to make sure that HomeKit will only show 'On' status when the power_state of the Apple TV is really 'PowerState.On' status.

Polling Interval : (The interval of seconds you want homekit to check for your Apple TV state)

Polling Timeout: 10
```

With this, if you or someone happen to turn the Apple TV off via the physical remote control, the status state would return 'PowerState.Off' and Homekit would then report that the Apple TV is off automatically. You can now using the Apple TV state to control your automation as you wish.

With this workaround, you don't need to create a bash script to run the commands and it should be easier for people who are looking for solution, at least it's easier for me.
