### ISSUE TITLE
Error: Cannot find module 'object-assign'

### ISSUE THREAD

**Issue by Laneville** [lukasroegner/homebridge-apple-tv-remote#50]
Trying to run the 'appletv pair' command to get my Apple tv's credentials.
I am receiving this error after just installing the package.

`pi@homebridge:/var/lib/homebridge $ appletv pair
internal/modules/cjs/loader.js:969
  throw err;
  ^

Error: Cannot find module 'object-assign'
Require stack:
- /usr/local/lib/node_modules/node-appletv-x/node_modules/cli-table3/src/utils.js
- /usr/local/lib/node_modules/node-appletv-x/node_modules/cli-table3/src/table.js
- /usr/local/lib/node_modules/node-appletv-x/node_modules/cli-table3/index.js
- /usr/local/lib/node_modules/node-appletv-x/node_modules/caporal/lib/help.js
- /usr/local/lib/node_modules/node-appletv-x/node_modules/caporal/lib/program.js
- /usr/local/lib/node_modules/node-appletv-x/node_modules/caporal/index.js
- /usr/local/lib/node_modules/node-appletv-x/dist/bin/index.js
- /usr/local/lib/node_modules/node-appletv-x/bin/appletv
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:966:15)
    at Function.Module._load (internal/modules/cjs/loader.js:842:27)
    at Module.require (internal/modules/cjs/loader.js:1026:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/node-appletv-x/node_modules/cli-table3/src/utils.js:1:22)
    at Module._compile (internal/modules/cjs/loader.js:1138:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)
    at Module.load (internal/modules/cjs/loader.js:986:32)
    at Function.Module._load (internal/modules/cjs/loader.js:879:14)
    at Module.require (internal/modules/cjs/loader.js:1026:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/node-appletv-x/node_modules/cli-table3/src/table.js:1:15)
    at Module._compile (internal/modules/cjs/loader.js:1138:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)
    at Module.load (internal/modules/cjs/loader.js:986:32)
    at Function.Module._load (internal/modules/cjs/loader.js:879:14) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/usr/local/lib/node_modules/node-appletv-x/node_modules/cli-table3/src/utils.js',
    '/usr/local/lib/node_modules/node-appletv-x/node_modules/cli-table3/src/table.js',
    '/usr/local/lib/node_modules/node-appletv-x/node_modules/cli-table3/index.js',
    '/usr/local/lib/node_modules/node-appletv-x/node_modules/caporal/lib/help.js',
    '/usr/local/lib/node_modules/node-appletv-x/node_modules/caporal/lib/program.js',
    '/usr/local/lib/node_modules/node-appletv-x/node_modules/caporal/index.js',
    '/usr/local/lib/node_modules/node-appletv-x/dist/bin/index.js',
    '/usr/local/lib/node_modules/node-appletv-x/bin/appletv'
  ]
}`

**Comment by lukasroegner** [comment]
Could be an outdated node version. On which version are you running?
