### ISSUE TITLE
reboot instance homebridge for Homebridge Apple Tv Remote

### ISSUE THREAD

**Issue by woofix** [lukasroegner/homebridge-apple-tv-remote#84]
Hi,

After installing the Homebridge Apple Tv Remote plugin to reboot homebridge indefinitely, do you have a tip?

[12/12/2020 à 11:56:41] TypeError: Cannot read property 'substr' of undefined
    at atvButton (/usr/lib/node_modules/homebridge-alexa/lib/parse/messages.js:1012:16)
    at Object.isAppleTV (/usr/lib/node_modules/homebridge-alexa/lib/parse/messages.js:981:83)
    at new Service (/usr/lib/node_modules/homebridge-alexa/lib/parse/Service.js:81:16)
    at Accessory.<anonymous> (/usr/lib/node_modules/homebridge-alexa/lib/parse/Accessory.js:38:23)
    at Array.forEach (<anonymous>)
    at new Accessory (/usr/lib/node_modules/homebridge-alexa/lib/parse/Accessory.js:24:20)
    at Homebridge.<anonymous> (/usr/lib/node_modules/homebridge-alexa/lib/parse/Homebridge.js:27:21)
    at Array.forEach (<anonymous>)
    at new Homebridge (/usr/lib/node_modules/homebridge-alexa/lib/parse/Homebridge.js:26:35)
    at Homebridges.<anonymous> (/usr/lib/node_modules/homebridge-alexa/lib/parse/Homebridges.js:18:22)

**Comment by lighth1** [comment]
Hi, did you manage to resolve this issue somehow? Got the same issue...

**Comment by woofix** [comment]
Hi, no I have to deactivate the plugin

**Comment by johnlietzke** [comment]
I am also receiving this message when the On/Off TV is selected.

`TypeError: Cannot read property 'substr' of undefined
    at atvButton (/usr/local/lib/node_modules/homebridge-alexa/lib/parse/messages.js:1012:16)
    at Object.isAppleTV (/usr/local/lib/node_modules/homebridge-alexa/lib/parse/messages.js:981:83)
    at new Service (/usr/local/lib/node_modules/homebridge-alexa/lib/parse/Service.js:81:16)
    at Accessory.<anonymous> (/usr/local/lib/node_modules/homebridge-alexa/lib/parse/Accessory.js:38:23)
    at Array.forEach (<anonymous>)
    at new Accessory (/usr/local/lib/node_modules/homebridge-alexa/lib/parse/Accessory.js:24:20)
    at Homebridge.<anonymous> (/usr/local/lib/node_modules/homebridge-alexa/lib/parse/Homebridge.js:27:21)
    at Array.forEach (<anonymous>)
    at new Homebridge (/usr/local/lib/node_modules/homebridge-alexa/lib/parse/Homebridge.js:26:35)
    at Homebridges.<anonymous> (/usr/local/lib/node_modules/homebridge-alexa/lib/parse/Homebridges.js:18:22)
    at Array.forEach (<anonymous>)
    at new Homebridges (/usr/local/lib/node_modules/homebridge-alexa/lib/parse/Homebridges.js:17:11)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge-alexa/lib/alexaActions.js:99:17)
    at HAPNodeJSClient.HAPaccessories (/usr/local/lib/node_modules/homebridge-alexa/node_modules/hap-node-client/HAPNodeJSClient.js:207:3)
    at Object.alexaDiscovery (/usr/local/lib/node_modules/homebridge-alexa/lib/alexaActions.js:95:14)
    at HAPNodeJSClient.<anonymous> (/usr/local/lib/node_modules/homebridge-alexa/lib/alexaActions.js:36:20)
    at HAPNodeJSClient.emit (events.js:315:20)
    at HAPNodeJSClient.<anonymous> (/usr/local/lib/node_modules/homebridge-alexa/node_modules/hap-node-client/HAPNodeJSClient.js:116:10)
    at Timeout._onTimeout (/usr/local/lib/node_modules/homebridge-alexa/node_modules/hap-node-client/HAPNodeJSClient.js:190:7)
    at listOnTimeout (internal/timers.js:554:17)
    at processTimers (internal/timers.js:497:7)`
